apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  labels:
    app.kubernetes.io/name: ingestion-service
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingestion-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
