apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
