apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
spec:
  volumeClaimTemplates:
    - metadata:
        name: valkey-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
