apiVersion: v1
kind: ConfigMap
metadata:
  name: insights-api-config
  labels:
    app.kubernetes.io/name: insights-api
data:
  CLICKHOUSE_HOST: clickhouse
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_USER: ollive
  CLICKHOUSE_DB: ollive
