apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse-ollive
    isDefault: true
    jsonData:
      defaultDatabase: ollive
      port: 9000
      host: clickhouse
      username: ollive
      protocol: native
      secure: false
    secureJsonData:
      password: ollivepass
    editable: true
